use_default_settings:
  engines:
    remove:
      - google
      - google images
      - google news
      - google videos
      - google scholar
      - google play movies
      - bing
      - bing images
      - bing news
      - bing videos

general:
  instance_name: "Degoog Search"

search:
  safe_search: 2
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "replace-this-with-a-long-random-secret-key"
  limiter: false
  image_proxy: true
